backend:
  name: git-gateway
  repo: alex-munayyer/portfolio-project-plume
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home Page Content"
      name: "Home Page Content"
      file: "content/home.md"
      fields:
        - { label: "Title Tag", name: "titleTag", widget: "string"}
        - { label: "Meta Description", name: "metaDescription", widget: "string"}