backend:
  name: git-gateway
  repo: alex-munayyer/portfolio-project-plume
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home Page Content"
      name: "Home Page Content"
      file: "content/home.md"
      fields:
        - { label: "Title Tag", name: "titleTag", widget: "string"}
        - { label: "Meta Description", name: "metaDescription", widget: "string"}
        - { label: "OG Title", name: "ogTitle", widget: "string"}
        - { label: "OG Description", name: "ogDescription", widget: "string"}
        - { label: "OG Image", name: "ogImage", widget: "image"}
        - { label: "Twitter Title", name: "twitterTitle", widget: "string"}
        - { label: "Twitter Description", name: "twitterDescription", widget: "string"}
        - { label: "Twitter Image", name: "twitterImage", widget: "image"}